' https://www.oauth.com/playground/

@startuml
participant "Robotic Client" as C 
participant "Security Provider" as SP 
participant "Resource Server" as RS 


== OAuth 2: Client credentials ==

' https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/

C -> SP: \nPOST /token HTTP/1.1\nHost: authorization-server.com\ngrant_type=client_credentials\n&client_id=xxxxxxxxxx\n&client_secret=xxxxxxxxxx
SP --> C: \nHTTP/1.1 200 OK\nContent-Type: application/json\nCache-Control: no-store\n {\n  "access_token":"MTQ0NjJkZmQ5OTM2NDE1ZTZjNGZmZjI3",\n  "token_type":"Bearer",\n  "expires_in":3600,\n  "refresh_token":"IwOGYzYTlmM2YxOTQ5MGE3YmNmMDFkNTVk",\n  "scope":"create"\n }
alt
C -> RS: Get resource from the server using the token
else
C -> SP: Get user info + permission from access token
SP --> C: user infos + permission in Security Provider specific format
C -> C: Verify permssion 
C -> C: Perform action
C --> C: Answer
end
