@startuml
participant Client as C
participant "Security Provider Company" as SP1 #Cyan
participant "Server Company" as S #Cyan

== OAuth 2.0 + OpenID : Single server ==

C -> SP1: Get Access token + ID token (id token = jwt) (login) for a given scope
SP1 --> C: Access Token + ID token (for a given scope)
C -> S: Send Action + Access token + ID token 
S -> S: Retrieve public key of security provider 
S -> S: Integrity check of ID token based on the pair (TLS Certificate or Public key, Access token)
S -> S: Get user info + permission from ID token 
S -> S: Verify permission 
S -> S: Perform action
S --> C: Answer to client  

' For server to accept ID token from google we just need to use a public certificate from google
' (the one which was used to sign the token)

' Security provider and server can be 2 different companies
' But we have to duplicate the permission in each security provider we implement

@enduml

' openid + author code:does this exist?
' https://youtu.be/996OiexHze0
' https://www.oauth.com/oauth2-servers/background/'
' we could watch video and perfrom diagram