' https://www.oauth.com/playground/

@startuml
participant "Robotic Client" as C 
participant "Security Provider" as SP 
participant "Resource Server" as RS 


== OAuth 2: Password grant ==

' https://developer.okta.com/blog/2018/06/29/what-is-the-oauth2-password-grant
' The Password grant requires that the application collect the user’s password. This is of course the exact problem that OAuth was created to avoid in the first place. So why is the Password grant included as part of OAuth?
' The original reason the Password grant was added to OAuth was to allow pre-OAuth applications to upgrade to OAuth without any user interaction. 

C -> SP: POST /oauth/token HTTP/1.1 \nHost: authorization-server.com \nContent-type: application/x-www-form-urlencoded \n \ngrant_type=password \n&username=exampleuser \n&password=1234luggage \n&client_id=xxxxxxxxxx

SP --> C: {\n  "access_token": "MTQ0NjOkZmQ5OTM5NDE9ZTZjNGZmZjI3", \n  "token_type": "bearer", \n  "expires_in": 3600, \n  "scope": "create" \n} 
C -> RS: Get resource from the server using the token
else
C -> SP: Get user info + permission from access token
SP --> C: user infos + permission in Security Provider specific format
C -> C: Verify permssion 
C -> C: Perform action
C --> C: Answer
end
